@echo off
REM %1 : CommonName(FQDN)
REM %2 : Certificate Store Path
REM %3 : Certificate.pfx FullPath
REM See https://github.com/PKISharp/win-acme/wiki/Install-script

if "%~3" == "" (
    echo Usage: %~nx0 CommonName CertStorePath CertPfxFullPath
    exit /b
)

REM Configurations
REM CERT_PFX is like %ProgramData%\win-acme\httpsacme-v01.api.letsencrypt.org\%COMMON_NAME%-all.pfx
REM CERT_ACME_PATH is like %ProgramData%\win-acme\httpsacme-v01.api.letsencrypt.org
setlocal
set COMMON_NAME=%~1
set CERT_STORE_PATH=%~2
set CERT_PFX=%~3
set CERT_PFX_PATH_=%~dp3
set CERT_PFX_NAME=%~nx3
set CERT_ACME_PATH=%CERT_PFX_PATH_:~0,-1%

set CERT_FULLCHAIN_NAME=%COMMON_NAME%-chain.pem
set CERT_PRIVATEKEY_NAME=%COMMON_NAME%-key.pem
set CERT_TRUSTED_NAME=ca-%COMMON_NAME%-crt.pem

set CERT_FILE_LIST=%CERT_PFX_NAME%,%CERT_FULLCHAIN_NAME%,%CERT_PRIVATEKEY_NAME%,%CERT_TRUSTED_NAME%
set NGINX_SSL_CERT_CONF=%CERT_STORE_PATH%\nginx_ssl_cert.conf

echo Store Certificate by %~f0
echo COMMON_NAME = %COMMON_NAME%
echo CERT_ACME_PATH = %CERT_ACME_PATH%
echo CERT_STORE_PATH = %CERT_STORE_PATH%
echo CERT_PFX = %CERT_PFX%

pushd %CERT_ACME_PATH%
for %%f in ( %CERT_FILE_LIST% ) do (
    echo. copy /Y "%%~f" "%CERT_STORE_PATH%\"
    copy /Y "%%~f" "%CERT_STORE_PATH%\"
)
popd

echo # DO NOT EDIT THIS FILE.> "%NGINX_SSL_CERT_CONF%"
echo # This file will be generated by storepem.cmd when renew certificate.>> "%NGINX_SSL_CERT_CONF%"
echo ssl_certificate         "%CERT_STORE_PATH%\%CERT_FULLCHAIN_NAME%";>> "%NGINX_SSL_CERT_CONF%"
echo ssl_certificate_key     "%CERT_STORE_PATH%\%CERT_PRIVATEKEY_NAME%";>> "%NGINX_SSL_CERT_CONF%"
echo ssl_trusted_certificate "%CERT_STORE_PATH%\%CERT_TRUSTED_NAME%";>> "%NGINX_SSL_CERT_CONF%"

echo Restart Nginx
REM See https://nssm.cc/usage
nssm stop nginx 2> NUL
nssm start nginx
