@echo off
REM %1 : CommonName(FQDN)
REM %2 : Certificate Store Path
REM See https://github.com/PKISharp/win-acme/wiki/Install-script

if "%~2" == "" (
    echo Usage: %~nx0 CommonName CertStorePath
    exit /b
)

REM Configurations
setlocal
set COMMON_NAME=%~1
set CERT_STORE_PATH=%~2

set CERT_FULLCHAIN_NAME=%COMMON_NAME%-chain.pem
set CERT_PRIVATEKEY_NAME=%COMMON_NAME%-key.pem

set CERT_FILE_LIST=%CERT_FULLCHAIN_NAME%,%CERT_PRIVATEKEY_NAME%
set NGINX_SSL_CERT_CONF=%CERT_STORE_PATH%\nginx_ssl_cert.conf

REM Store certificate to certificate store path.
echo Store Certificate by %~f0
echo COMMON_NAME = %COMMON_NAME%
echo CERT_STORE_PATH = %CERT_STORE_PATH%

echo # DO NOT EDIT THIS FILE.> "%NGINX_SSL_CERT_CONF%"
echo # This file will be generated by storepem.cmd when renew certificate.>> "%NGINX_SSL_CERT_CONF%"
echo ssl_certificate         "%CERT_STORE_PATH%\%CERT_FULLCHAIN_NAME%";>> "%NGINX_SSL_CERT_CONF%"
echo ssl_certificate_key     "%CERT_STORE_PATH%\%CERT_PRIVATEKEY_NAME%";>> "%NGINX_SSL_CERT_CONF%"

echo Restart Nginx
REM See https://nssm.cc/usage
nssm stop nginx 2> NUL
nssm start nginx
